[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xtask"
path = "main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = [
    "std",
    "help",
    "env",
    "derive",
    "error-context",
] }
cruet = { version = "0.15", default-features = false }
dotenvy = { workspace = true }
inquire = { version = "0.8", default-features = false, features = [
    "crossterm",
] }
minijinja = { version = "2.11", default-features = false, features = [
    "serde",
    "loader",
    "builtins",
] }

prettyplease = { version = "0.2", default-features = false }
proc-macro2 = { version = "1.0", default-features = false }
quote = { version = "1.0", default-features = false, features = ["proc-macro"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
sqlx = { workspace = true, features = [
    "runtime-tokio",
    "postgres",
    "macros",
    "derive",
] }
syn = { version = "2.0", default-features = false, features = [
    "full",
    "parsing",
    "printing",
] }
tokio = { workspace = true, features = ["full"] }
walkdir = { version = "2.5", default-features = false }
