[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[[bin]]
name = "server"
path = "main.rs"

[features]
default = [
    "kv_redb",
    "bg_postgres",
    "object_storage_fs",
    "trace_console",
    "serve_with_sched",
]
kv_redb = ["infrastructure/kv_redb"]
kv_redis = ["infrastructure/kv_redis"]
bg_sqlite = ["infrastructure/bg_sqlite"]
bg_postgres = ["infrastructure/bg_postgres"]
object_storage_fs = ["infrastructure/object_storage_fs"]
object_storage_s3 = ["infrastructure/object_storage_s3"]
object_storage_s3_tls = [
    "object_storage_s3",
    "infrastructure/object_storage_s3_tls",
]
trace_console = ["trace_kit/console"]
trace_rolling = ["trace_kit/rolling", "infrastructure/trace_rolling"]
trace_otlp = [
    "trace_kit/otlp",
    "adapter/trace_otlp",
    "infrastructure/trace_otlp",
]
trace_otlp_tls = ["trace_otlp", "trace_kit/otlp_tls"]
serve_with_sched = []
flag_flipt = ["infrastructure/flag_flipt"]
test = [
    "kv_redb",
    "bg_sqlite",
    "object_storage_fs",
    "trace_console",
    "serve_with_sched",
    "infrastructure/test",
]

[dependencies]
adapter = { workspace = true }
anyhow = { workspace = true }
application = { workspace = true }
axum = { workspace = true }
bg_worker_kit = { workspace = true }
chrono-tz = { workspace = true }
clap = { workspace = true, features = [
    "std",
    "help",
    "env",
    "derive",
    "error-context",
] }
dotenvy = { workspace = true }
humantime = { workspace = true }
infrastructure = { workspace = true }
kvdb_kit = { workspace = true }
mimalloc = { workspace = true }
object_storage_kit = { workspace = true }
sched_kit = { workspace = true }
tokio = { workspace = true, features = ["full"] }
trace_kit = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }
