[package]
name = "server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "main.rs"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = [
    "std",
    "help",
    "env",
    "derive",
    "error-context",
] }
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true }
dotenvy = { workspace = true }
chrono-tz = { workspace = true }
mimalloc = { workspace = true }
humantime = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "ansi",
    "env-filter",
    "json",
] }

adapter = { workspace = true }
application = { workspace = true }
infrastructure = { workspace = true }
bg_worker = { workspace = true }

[features]
default = ["kv_redis", "bg_dummy"]
kv_redb = ["infrastructure/kv_redb"]
kv_redis = ["infrastructure/kv_redis"]
bg_dummy = ["infrastructure/bg_dummy"]
bg_faktory = ["infrastructure/bg_faktory"]
