[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[[bin]]
name = "server"
path = "main.rs"

[features]
default = ["kv_redb", "bg_dummy", "object_storage_fs"]
kv_redb = ["infrastructure/kv_redb"]
kv_redis = ["infrastructure/kv_redis"]
bg_dummy = ["infrastructure/bg_dummy"]
bg_faktory = ["infrastructure/bg_faktory"]
object_storage_fs = ["infrastructure/object_storage_fs"]
object_storage_s3 = ["infrastructure/object_storage_s3"]

[dependencies]

kvdb = { workspace = true }
adapter = { workspace = true }
anyhow = { workspace = true }
application = { workspace = true }
axum = { workspace = true }
bg_worker = { workspace = true }
chrono-tz = { workspace = true }
clap = { workspace = true, features = [
    "std",
    "help",
    "env",
    "derive",
    "error-context",
] }
dotenvy = { workspace = true }
humantime = { workspace = true }
infrastructure = { workspace = true }
mimalloc = { workspace = true }
object_storage = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "ansi",
    "env-filter",
    "json",
] }
