services:
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - $PWD/containers/pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  rustfs:
    image: rustfs/rustfs:alpha
    restart: always
    ports:
      - "9000:9000"
    environment:
      - FAKTORY_PASSWORD=123123
    volumes:
      - $PWD/containers/rustfs:/data

  faktory:
    image: contribsys/faktory
    restart: always
    ports:
      - "7419:7419"
      - "7420:7420"
    environment:
      - FAKTORY_PASSWORD=123123
    volumes:
      - $PWD/containers/faktory:/var/lib/faktory/db
    command: /faktory -b :7419 -w :7420 -e production
