[package]
name = "trace_kit"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[features]
console = []
rolling = ["dep:tracing-appender", "tracing-subscriber/json"]
otel = []

[dependencies]
bon = { workspace = true }
tracing-appender = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "ansi",
    "env-filter",
] }
