[package]
name = "migrate_kit"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
include_dir = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
