[package]
name = "event_kit"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
