[package]
name = "single_flight_derive"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = { version = "2.0" }
quote = { version = "1.0" }
proc-macro2 = { version = "1.0" }
cruet = { workspace = true }
