[package]
name = "cache_kit_macros"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
humantime = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
