name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U test -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://test:test@127.0.0.1:5432/test_db
      SQLX_OFFLINE: true

    steps:
      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Clone code
        uses: actions/checkout@v4
      - name: Backend test
        run: |
          cargo llvm-cov nextest --workspace --lcov > lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          toolchain: stable
          override: true

      - name: Install musl-tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: musl-tools
          version: 1.0

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
            node_modules/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: Build frontend
        run: cd frontend && bun install && bun run build

      - name: Build x86_64-unknown-linux-musl
        run: |
          cargo build --package server --release --target x86_64-unknown-linux-musl --locked
          ls -lh target/x86_64-unknown-linux-musl/release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: server_x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release/server
          retention-days: 7
