name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          toolchain: stable
          override: true

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install musl-tools
        run: sudo apt-get update -y && sudo apt-get install -y musl-tools

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
            node_modules/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build frontend
        run: cd frontend && pnpm install && pnpm run build

      - name: Build x86_64-unknown-linux-musl
        run: |
          cargo build --package server --release --target x86_64-unknown-linux-musl --locked
          ls -lh target/x86_64-unknown-linux-musl/release
